# Generated by Django 5.0.1 on 2024-01-07 21:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Workouts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workout_name', models.CharField(blank=True, max_length=64)),
                ('date', models.DateTimeField(blank=True)),
                ('duration', models.IntegerField(blank=True)),
                ('set_order', models.IntegerField(blank=True)),
                ('weight', models.FloatField(blank=True)),
                ('reps', models.IntegerField(blank=True)),
                ('distance', models.FloatField(blank=True)),
                ('seconds', models.IntegerField(blank=True)),
                ('notes', models.CharField(blank=True, max_length=256)),
                ('workout_notes', models.CharField(blank=True, max_length=256)),
                ('rpe', models.FloatField(blank=True, null=True)),
                ('exercise_name', models.CharField(blank=True, max_length=64)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
