# Generated by Django 5.0.1 on 2024-01-08 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness_api', '0004_rename_workouts_workout'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='abdominals',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workout',
            name='arms',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workout',
            name='back',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workout',
            name='chest',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workout',
            name='legs',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workout',
            name='shoulders',
            field=models.BooleanField(default=False),
        ),
    ]
