# Generated by Django 3.0.8 on 2024-01-18 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness_api', '0005_workout_abdominals_workout_arms_workout_back_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workout',
            old_name='shoulders',
            new_name='abdominal_head',
        ),
        migrations.AddField(
            model_name='workout',
            name='adductors',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workout',
            name='aerobics',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workout',
            name='anterior_deltoids',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workout',
            name='biceps',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workout',
            name='calves',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workout',
            name='clavicular_head',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workout',
            name='glutes',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workout',
            name='hamstrings',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workout',
            name='lateral_deltoids',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workout',
            name='lats',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workout',
            name='mid_back',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workout',
            name='mid_traps',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workout',
            name='posterior_deltoids',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workout',
            name='quads',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workout',
            name='rhomboids',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workout',
            name='shoulder',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workout',
            name='sternal_head',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workout',
            name='triceps',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workout',
            name='upper_traps',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='workout',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
