# Generated by Django 3.0.8 on 2024-01-18 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fitness_api', '0006_auto_20240118_0054'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workout',
            name='aerobics',
        ),
        migrations.RemoveField(
            model_name='workout',
            name='arms',
        ),
    ]
